In [1]:
import csv
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
jobs = pd.read_csv('occupations.csv')

#transfer the H_MEAN or A_MEAN or JOBS_1000 number from string to float
jobs['A_MEAN'] = jobs['A_MEAN'].str.replace(',', '')
jobs['TOT_EMP'] = jobs['TOT_EMP'].str.replace(',', '')
jobs['A_MEAN'] = pd.to_numeric(jobs.A_MEAN, errors='coerce')
jobs['H_MEAN'] = pd.to_numeric(jobs.H_MEAN, errors='coerce')
jobs['TOT_EMP'] = pd.to_numeric(jobs.TOT_EMP, errors='coerce')

#drop the word'Occupations' in each row of OCC_TITLE
jobs['OCC_TITLE'] = jobs['OCC_TITLE'].str.replace('Occupations', '')

#delete the rows without value
job=jobs[jobs['H_MEAN'].notnull() & jobs['A_MEAN'].notnull()]

#filter the data without'major'
major = job[job['OCC_GROUP'].str.contains('major')]
major.head()

,PRIM_STATE,AREA,AREA_NAME,OCC_CODE,OCC_TITLE,OCC_GROUP,TOT_EMP,EMP_PRSE,JOBS_1000,LOC QUOTIENT,...,H_MEDIAN,H_PCT75,H_PCT90,A_PCT10,A_PCT25,A_MEDIAN,A_PCT75,A_PCT90,ANNUAL,HOURLY
1,CA,31080,"Los Angeles-Long Beach-Anaheim, CA",11-0000,Management,major,330970.0,1.1,57.225,1.13,...,53.29,77.60,#,"48,320","72,550","110,850","161,410",#,NaN,NaN
34,CA,31080,"Los Angeles-Long Beach-Anaheim, CA",13-0000,Business and Financial Operations,major,352020.0,1.3,60.864,1.17,...,34.59,46.82,61.48,"38,840","52,850","71,950","97,380","127,870",NaN,NaN
66,CA,31080,"Los Angeles-Long Beach-Anaheim, CA",15-0000,Computer and Mathematical,major,161410.0,2.6,27.908,0.94,...,42.65,57.34,71.71,"43,460","61,660","88,710","119,270","149,160",NaN,NaN
85,CA,31080,"Los Angeles-Long Beach-Anaheim, CA",17-0000,Architecture and Engineering,major,100720.0,2.5,17.414,0.98,...,43.20,58.19,74.02,"49,820","66,190","89,850","121,040","153,960",NaN,NaN
120,CA,31080,"Los Angeles-Long Beach-Anaheim, CA",19-0000,"Life, Physical, and Social Science",major,47570.0,6.1,8.225,1.00,...,33.62,47.08,59.46,"34,950","47,500","69,930","97,930","123,680",NaN,NaN

In [4]:
#delete the rows without value
job_TOTEMP=jobs[jobs['TOT_EMP'].notnull()]

#filter the data without'major'
major_TOTEMP = job_TOTEMP[job_TOTEMP['OCC_GROUP'].str.contains('major')]
major_TOTEMP.head()

,PRIM_STATE,AREA,AREA_NAME,OCC_CODE,OCC_TITLE,OCC_GROUP,TOT_EMP,EMP_PRSE,JOBS_1000,LOC QUOTIENT,...,H_MEDIAN,H_PCT75,H_PCT90,A_PCT10,A_PCT25,A_MEDIAN,A_PCT75,A_PCT90,ANNUAL,HOURLY
1,CA,31080,"Los Angeles-Long Beach-Anaheim, CA",11-0000,Management,major,330970.0,1.1,57.225,1.13,...,53.29,77.60,#,"48,320","72,550","110,850","161,410",#,NaN,NaN
34,CA,31080,"Los Angeles-Long Beach-Anaheim, CA",13-0000,Business and Financial Operations,major,352020.0,1.3,60.864,1.17,...,34.59,46.82,61.48,"38,840","52,850","71,950","97,380","127,870",NaN,NaN
66,CA,31080,"Los Angeles-Long Beach-Anaheim, CA",15-0000,Computer and Mathematical,major,161410.0,2.6,27.908,0.94,...,42.65,57.34,71.71,"43,460","61,660","88,710","119,270","149,160",NaN,NaN
85,CA,31080,"Los Angeles-Long Beach-Anaheim, CA",17-0000,Architecture and Engineering,major,100720.0,2.5,17.414,0.98,...,43.20,58.19,74.02,"49,820","66,190","89,850","121,040","153,960",NaN,NaN
120,CA,31080,"Los Angeles-Long Beach-Anaheim, CA",19-0000,"Life, Physical, and Social Science",major,47570.0,6.1,8.225,1.00,...,33.62,47.08,59.46,"34,950","47,500","69,930","97,930","123,680",NaN,NaN

In [5]:
#caulculate the average of income per hour/year of occupations in U.S. major states
sum_TOTEMP = major_TOTEMP.groupby(['OCC_TITLE'])[['TOT_EMP']].sum()
print(sum_TOTEMP)

                                                   TOT_EMP
OCC_TITLE
Architecture and Engineering                      663360.0
Arts, Design, Entertainment, Sports, and Media    770650.0
Building and Grounds Cleaning and Maintenance    1226000.0
Business and Financial Operations                2574460.0
Community and Social Service                      578040.0
Computer and Mathematical                        1571500.0
Construction and Extraction                      1368400.0
Education, Training, and Library                 2455050.0
Farming, Fishing, and Forestry                     27430.0
Food Preparation and Serving Related             3438370.0
Healthcare Practitioners and Technical           2210360.0
Healthcare Support                               1185370.0
Installation, Maintenance, and Repair            1322000.0
Legal                                             440310.0
Life, Physical, and Social Science                374520.0
Management                                       2346940.0
Office and Administrative Support                6440490.0
Personal Care and Service                        1294110.0
Production                                       1940830.0
Protective Service                               1042900.0
Sales and Related                                4109520.0
Transportation and Material Moving               2566660.0

In [6]:
# Create a pie chart
plt.pie(
    # using data sum_TOTEMP
    sum_TOTEMP['TOT_EMP'],
    # with the labels being officer names
    labels=sum_TOTEMP['OCC_TITLE'],
    # with no shadows
    shadow=False,
    # with the start angle at 10%
    startangle=10,
    # with the percent listed as a fraction
    autopct='%1.1f%%',
    )

# View the plot drop above
plt.axis('equal')

# View the plot
plt.tight_layout()
plt.show()

KeyError: 'OCC_TITLE'